'use client';
import {useEffect,useRef,useState} from 'react';
import {Send,MessageSquare,ShieldCheck,RefreshCw,ArrowUpRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {recordHash,type ProjectRecord} from '@/lib/ai-core';
import {ChatContextPicker} from './chat-context-picker';
import {useCloudDraft} from './use-cloud-draft';
export type AIJob={id:string;kind:string;recordId:string|null;contentHash:string|null;title:string;prompt:string;attachments?:{id:string;title:string;kind:string}[];output:string;status:string;error:string;createdAt:number;updatedAt:number;model:string};
export function useAssistant(){
 const [jobs,setJobs]=useState<AIJob[]>([]),[error,setError]=useState('');const processing=useRef(false);
 async function refresh(){try{const r=await fetch('/api/ai',{cache:'no-store'});if(!r.ok)throw Error('读取对话与审查记录失败。');const d=await r.json() as {jobs:AIJob[]};setJobs(d.jobs);setError('');return d.jobs;}catch(e){setError((e as Error).message);return[]}}
 async function action(input:unknown){const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const d=await r.json() as {jobs?:AIJob[];error?:string};if(!r.ok)throw Error(d.error||'请求失败，请重试。');if(d.jobs)setJobs(d.jobs);setError('');}
 useEffect(()=>{void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible'&&!processing.current)void refresh()},7000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(processing.current||!jobs.some(j=>j.status==='pending')||jobs.some(j=>j.status==='running'))return;processing.current=true;void action({action:'run'}).catch(e=>setError(e.message)).finally(()=>{processing.current=false;void refresh()});},[jobs]);
 // A terminated background call is reclaimed by the server on the next run request.
 useEffect(()=>{const timer=setInterval(()=>{if(!processing.current&&jobs.some(j=>j.status==='running'&&Date.now()-j.updatedAt>155000)){processing.current=true;void action({action:'run'}).catch(e=>setError(e.message)).finally(()=>{processing.current=false;void refresh()})}},10000);return()=>clearInterval(timer)},[jobs]);
 return{jobs,error,refresh,action};
}
function Answer({text}:{text:string}){return <div className="ai-answer">{text.split('\n').map((line,i)=>/^#{1,3} /.test(line)?<h3 key={i}>{line.replace(/^#{1,3} /,'')}</h3>:<p key={i}>{line.replace(/\*\*(.*?)\*\*/g,'$1')||'\u00a0'}</p>)}</div>}
export default function AssistantPanel({assistant,records,onOpen,draft}:{assistant:ReturnType<typeof useAssistant>;records:ProjectRecord[];onOpen:(id:string)=>void;draft:ReturnType<typeof useCloudDraft>}){
 const text=draft.text,selected=draft.recordIds;
 const [tab,setTab]=useState('chat'),[sending,setSending]=useState(false),[error,setError]=useState(''),[hashes,setHashes]=useState<Record<string,string>>({});const draftId=useRef<string|null>(null),historyRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{let alive=true;void Promise.all(records.map(async r=>[r.id,await recordHash(r)] as const)).then(entries=>{if(alive)setHashes(Object.fromEntries(entries))});return()=>{alive=false}},[records]);
 const chats=assistant.jobs.filter(j=>j.kind==='chat').sort((a,b)=>a.createdAt-b.createdAt),reviews=assistant.jobs.filter(j=>j.kind==='review');
 useEffect(()=>{historyRef.current?.scrollTo({top:historyRef.current.scrollHeight})},[chats.length]);
 async function send(){const message=text.trim()||(selected.length?'请先阅读我选的资料，指出规则冲突、遗漏和待确认问题，然后问我接下来想聚焦什么。':'');if(!message||sending)return;setSending(true);setError('');draftId.current??='chat-'+crypto.randomUUID();try{await assistant.action({action:'chat',id:draftId.current,message,recordIds:selected});draft.setText('');void draft.flush();draftId.current=null;}catch(e){setError((e as Error).message)}finally{setSending(false)}}
 async function retry(id:string){try{await assistant.action({action:'retry',id});setError('')}catch(e){setError((e as Error).message)}}
 function status(j:AIJob){return j.status==='done'?'已完成':j.status==='failed'?'处理失败':j.status==='running'?'Kimi 正在分析…':'等待审查 / 回复'}
 return <section className="ai-workspace"><div className="toolbar"><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="chat"><MessageSquare size={16}/>橡皮鸭对话</TabsTrigger><TabsTrigger value="reviews"><ShieldCheck size={16}/>自动审查 · {reviews.length}</TabsTrigger></TabsList></Tabs><span className="tag violet">Kimi K3 · 云端保存</span><button className="text-button" onClick={()=>void assistant.refresh()}><RefreshCw size={14}/>刷新</button></div><p className="ai-scope">讨论会参考当前项目资料和原始用户发言。模型只审查与提问，不会擅自修改设定或文档。</p>{draft.status==='conflict'&&<div className="draft-conflict" role="alert">草稿在另一设备更新过。<button onClick={draft.useRemote}>使用云端草稿</button><button onClick={draft.keepLocal}>保留本机草稿并同步</button></div>}{draft.status==='error'&&<p className="draft-error" role="status">草稿暂时未同步，正在重试。</p>}{(error||assistant.error)&&<div className="error" role="alert">{error||assistant.error}</div>}
 {tab==='chat'?<><ChatContextPicker records={records} selected={selected} onChange={ids=>{draft.setRecordIds(ids);draftId.current=null}}/><div className="chat-history" ref={historyRef} aria-live="polite">{!chats.length&&<div className="ai-empty"><MessageSquare size={30}/><h2>把正在想的规则放在这里。</h2><p>例如：“我想让 GAP 焦虑到阈值后强制回家，和现有规则冲突吗？”</p></div>}{chats.map(j=><article className="chat-turn" key={j.id}><div className="chat-user"><small>你 · {new Date(j.createdAt).toLocaleString('zh-CN')}</small><p>{j.prompt}</p>{!!j.attachments?.length&&<div className="chat-attached"><small>讨论资料：</small>{j.attachments.map(a=><button type="button" key={a.id} onClick={()=>onOpen(a.id)}>{a.title}</button>)}</div>}</div><div className="chat-assistant"><small>橡皮鸭 · {j.model} · {status(j)}</small>{j.output?<Answer text={j.output}/>:<p className="ai-pending">{j.error||'消息已保存到云端，等待模型回复。离开页面不会丢失消息，返回后可继续处理。'}</p>}{j.status==='failed'&&<button className="text-button" onClick={()=>void retry(j.id)}>重试这条消息</button>}</div></article>)}</div><form className="chat-compose" onSubmit={e=>{e.preventDefault();void send()}}><label htmlFor="duck-message">继续讨论</label><textarea id="duck-message" value={text} maxLength={6000} onChange={e=>{draft.setText(e.target.value);draftId.current=null}} placeholder="说出你的想法、规则或疑问；只选资料也可以直接发送。" rows={4}/><div><span>{text.length} / 6000 · 草稿{draft.status==='synced'?'已跨设备同步':draft.status==='saving'?'保存中':'待同步'}</span><button className="button primary" disabled={sending||(!text.trim()&&!selected.length)}><Send size={16}/>{sending?'发送中…':'发送给橡皮鸭'}</button></div></form></>:<div className="reviews-list">{!reviews.length&&<div className="ai-empty"><ShieldCheck size={30}/><h2>新建内容后会自动进入这里。</h2><p>编辑正文也会触发审查。旧记录可在详情中点击“请橡皮鸭审查”。</p></div>}{reviews.map(j=><article className="review-card" key={j.id}><header><div><span className="eyebrow">{j.recordId} · {j.contentHash?.slice(0,8)}</span><h2>{j.title}</h2></div><span className={'tag '+(j.status==='failed'?'amber':'violet')}>{status(j)}</span></header>{hashes[j.recordId||'']&&hashes[j.recordId||'']!==j.contentHash&&<p className="stale-review">此审查针对旧版内容，记录已有变化。请查看最新审查。</p>}{!records.some(r=>r.id===j.recordId)&&<p className="stale-review">原记录已删除，此处保留历史审查。</p>}{j.output?<Answer text={j.output}/>:<p className="ai-pending">{j.error||'内容已保存。审查排队中，完成后会出现在这里。'}</p>}<footer><span>{new Date(j.createdAt).toLocaleString('zh-CN')} · {j.model}</span><button className="text-button" onClick={()=>onOpen(j.recordId||'')}>查看记录 <ArrowUpRight size={14}/></button>{j.status==='failed'&&<button className="text-button" onClick={()=>void retry(j.id)}>重试</button>}</footer></article>)}</div>}
 <p className="ai-history-note">显示最近 300 条对话与审查。审查结果是建议，不等于规则已确认或制作已验收。</p></section>;
}
