'use client';
import {useEffect,useRef,useState} from 'react';
type Draft={text:string;recordIds:string[];revision:number};
type Status='loading'|'synced'|'unsaved'|'saving'|'error'|'conflict';
export function useCloudDraft(){
 const [text,setTextState]=useState(''),[recordIds,setIdsState]=useState<string[]>([]),[status,setStatus]=useState<Status>('loading'),[conflict,setConflict]=useState<Draft|null>(null);
 const current=useRef({text:'',recordIds:[] as string[]}),revision=useRef(0),ready=useRef(false),dirty=useRef(false),saving=useRef(false),version=useRef(0),timer=useRef<ReturnType<typeof setTimeout>|null>(null),conflictRef=useRef<Draft|null>(null);
 function schedule(delay=650){if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{void flush()},delay)}
 function apply(d:Draft){revision.current=d.revision;current.current={text:d.text,recordIds:d.recordIds};setTextState(d.text);setIdsState(d.recordIds);dirty.current=false;setStatus('synced')}
 async function refresh(){try{const r=await fetch('/api/ai/draft',{cache:'no-store'});if(!r.ok)throw Error('draft_read_failed');const d=await r.json() as Draft;if(!ready.current){ready.current=true;if(dirty.current){revision.current=d.revision;if(current.current.text&&d.text&&current.current.text!==d.text){conflictRef.current=d;setConflict(d);setStatus('conflict');return}const merged={text:current.current.text||d.text,recordIds:[...new Set([...current.current.recordIds,...d.recordIds])].slice(0,8)};current.current=merged;setTextState(merged.text);setIdsState(merged.recordIds);schedule(0)}else apply(d)}else if(!dirty.current&&!saving.current&&!conflictRef.current&&d.revision>revision.current)apply(d)}catch{if(!ready.current)setStatus('error')}}
 async function flush(){if(!ready.current||!dirty.current||saving.current||conflictRef.current)return;saving.current=true;setStatus('saving');const serial=version.current,snapshot={...current.current,revision:revision.current};let failed=false;try{const r=await fetch('/api/ai/draft',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot)});const d=await r.json() as Draft&{draft?:Draft};if(r.status===409&&d.draft){conflictRef.current=d.draft;setConflict(d.draft);setStatus('conflict');return}if(!r.ok)throw Error('draft_save_failed');revision.current=d.revision;if(version.current===serial){dirty.current=false;setStatus('synced')}else setStatus('unsaved')}catch{failed=true;setStatus('error')}finally{saving.current=false;if(dirty.current&&!conflictRef.current)schedule(failed?4000:650)}}
 function setText(value:string){if(current.current.text===value)return;current.current={...current.current,text:value};version.current++;dirty.current=true;setTextState(value);setStatus('unsaved');schedule()}
 function setRecordIds(value:string[]|((ids:string[])=>string[])){const next=typeof value==='function'?value(current.current.recordIds):value;if(JSON.stringify(next)===JSON.stringify(current.current.recordIds))return;current.current={...current.current,recordIds:next};version.current++;dirty.current=true;setIdsState(next);setStatus('unsaved');schedule()}
 function useRemote(){if(!conflictRef.current)return;apply(conflictRef.current);conflictRef.current=null;setConflict(null)}
 function keepLocal(){if(!conflictRef.current)return;revision.current=conflictRef.current.revision;conflictRef.current=null;setConflict(null);setStatus('unsaved');schedule(0)}
 useEffect(()=>{void refresh();const onFocus=()=>{if(document.visibilityState==='visible')void refresh()};window.addEventListener('focus',onFocus);document.addEventListener('visibilitychange',onFocus);const interval=setInterval(onFocus,15000);return()=>{window.removeEventListener('focus',onFocus);document.removeEventListener('visibilitychange',onFocus);clearInterval(interval);if(timer.current)clearTimeout(timer.current)}},[]);
 return{text,recordIds,status,conflict,setText,setRecordIds,refresh,flush,useRemote,keepLocal};
}
