'use client';
import {useEffect,useState,useRef} from 'react';
import {LayoutDashboard,Kanban,Lightbulb,Workflow,BookOpen,FolderOpen,Plus,ArrowUpRight,Search,Download,Check,ArrowRight,FileText,Image as ImageIcon,Clock,Flag,Link as LinkIcon,Pencil,Trash2,ChevronRight,PanelLeft,RefreshCw} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,SidebarInset} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription} from '@/components/ui/alert-dialog';
import {Progress} from '@/components/ui/progress';
import seed from '@/data/seed.json';
import sources from '@/data/sources.json';
import AssistantPanel,{useAssistant} from './assistant-panel';
import {validateRecords} from '@/lib/ai-core';
type RecordItem=typeof seed[number];
const nav=[['overview','项目总览',LayoutDashboard],['task','任务看板',Kanban],['idea','灵感收件箱',Lightbulb],['mechanic','机制设计',Workflow],['doc','GDD 文档',BookOpen],['source','原始资料',FolderOpen],['assistant','橡皮鸭对话与审查',Lightbulb]] as const;
const statuses=['待办','进行中','待验收','已完成'];
function Choice({value,options,onChange,label}:{value:string,options:string[],onChange:(v:string)=>void,label:string}){return <Select value={value} onValueChange={v=>v&&onChange(v)}><SelectTrigger aria-label={label}><SelectValue>{value}</SelectValue></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select>}
function download(name:string,content:string,type='text/plain'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function DocumentBody({text}:{text:string}){return <>{text.split('\n').map((line,i)=>line.startsWith('## ')?<h3 key={i}>{line.slice(3)}</h3>:line.startsWith('# ')?<h2 key={i}>{line.slice(2)}</h2>:line?<p key={i}>{line}</p>:<div className="paragraph-gap" key={i}/>)}</>}
export default function Workspace(){
const assistant=useAssistant();
const [incoming,setIncoming]=useState<RecordItem[]|null>(null),[overwrite,setOverwrite]=useState(false);const importInput=useRef<HTMLInputElement>(null);
function receiveBackup(data:unknown){const d=data as {version?:number;records?:unknown};if(d?.version!==1||!validateRecords(d.records)){setError('备份格式无效，请使用工作台导出的 JSON。');return;}setIncoming(d.records);setOverwrite(false);}
useEffect(()=>{const handler=(e:MessageEvent)=>{if(e.origin==='https://oarngeftansy.github.io'&&e.source===window.opener&&e.data?.type==='twenties-local-import')receiveBackup(e.data.backup)};window.addEventListener('message',handler);window.opener?.postMessage({type:'twenties-cloud-ready'},'https://oarngeftansy.github.io');return()=>window.removeEventListener('message',handler)},[]);
const [view,setView]=useState('overview'),[records,setRecords]=useState<RecordItem[]>(seed),[query,setQuery]=useState(''),[filter,setFilter]=useState('全部模块'),[connected,setConnected]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editing,setEditing]=useState<RecordItem|null>(null),[detail,setDetail]=useState<RecordItem|null>(null),[saving,setSaving]=useState(false),[remove,setRemove]=useState<RecordItem|null>(null),[sourceTab,setSourceTab]=useState('images'),[image,setImage]=useState<string|null>(null),[revision,setRevision]=useState(0);
const syncEpoch=useRef(0),busyRef=useRef(false);busyRef.current=!!editing||saving||!!incoming;
async function reload(quiet=false){const epoch=syncEpoch.current;if(!quiet)setLoading(true);try{const r=await fetch('/api/records');if(!r.ok)throw new Error('读取失败，请重试');const d=await r.json() as {records:RecordItem[],revision:number};if(quiet&&(busyRef.current||epoch!==syncEpoch.current))return;setRecords(d.records);setRevision(d.revision);setConnected(true);setError('');}catch(e){setConnected(false);setError('暂时无法读取已保存数据。当前显示导入资料，只读；请重试。');}finally{setLoading(false)}}
useEffect(()=>{void reload();},[]);
useEffect(()=>{const sync=()=>{if(document.visibilityState==='visible'&&!editing&&!saving&&!incoming)void reload(true)};window.addEventListener('focus',sync);document.addEventListener('visibilitychange',sync);const timer=setInterval(sync,30000);return()=>{window.removeEventListener('focus',sync);document.removeEventListener('visibilitychange',sync);clearInterval(timer)}},[editing,saving,incoming]);
useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(t)}},[notice]);
const recordRef=useRef(records);recordRef.current=records;
useEffect(()=>{
const mc=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!mc?.registerTool)return;
const lifecycle=new AbortController();
const registrations=[
{name:'search_project_records',title:'搜索项目记录',description:'搜索此工作台的任务、灵感、机制与GDD，返回来源与当前状态。',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){const q=input as {query?:unknown};if(typeof q?.query!=='string')throw new Error('query must be a string');return recordRef.current.filter(r=>[r.title,r.body,r.source].some(v=>v.includes(q.query as string))).map(({id,title,kind,status,source})=>({id,title,kind,status,source}));}},
{name:'open_project_record',title:'打开项目记录',description:'打开已有记录的详情，不修改已保存的数据。',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input:unknown){const q=input as {id?:unknown};if(typeof q?.id!=='string')throw new Error('id must be a string');const r=recordRef.current.find(r=>r.id===q.id);if(!r)throw new Error('record not found');setDetail(r);await new Promise(resolve=>requestAnimationFrame(()=>resolve(null)));return {id:r.id,opened:true};}}
];for(const tool of registrations){try{void Promise.resolve(mc.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}return()=>lifecycle.abort();
},[]);
const tasks=records.filter(r=>r.kind==='task'),done=tasks.filter(t=>t.status==='已完成').length,percent=tasks.length?Math.round(done/tasks.length*100):0;
const shown=records.filter(r=>r.kind===view).filter(r=>filter==='全部模块'||r.category===filter).filter(r=>[r.title,r.body,r.source,r.category,r.evidence].some(s=>s.toLowerCase().includes(query.toLowerCase())));
function go(v:string){setView(v);setQuery('');setFilter('全部模块');}
async function persist(next:RecordItem[],message:string){if(!connected||saving)return false;syncEpoch.current++;setSaving(true);try{const r=await fetch('/api/records',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({records:next,revision})});if(r.status===409)throw new Error('其他窗口已更新，请刷新后再编辑。当前输入仍保留。');if(!r.ok)throw new Error('保存失败，输入已保留，请重试。');const d=await r.json() as {revision:number;queuedReviews?:number};setRecords(next);setRevision(d.revision);setNotice(message+(d.queuedReviews?' · 橡皮鸭审查已排队':''));void assistant.refresh();setError('');return true;}catch(e){setError((e as Error).message);return false;}finally{setSaving(false)}}
function create(kind:string){setEditing({id:kind.toUpperCase()+'-'+crypto.randomUUID().slice(0,8),kind,title:'',category:filter==='全部模块'?'未分类':filter,body:'',source:'手动新增',evidence:'待确认',priority:'P1',status:kind==='task'?'待办':'待确认',owner:'',due:'',updatedAt:new Date().toISOString()})}
function evidence(r:RecordItem){return <span className={'tag '+(r.evidence==='待确认'?'amber':'violet')}>{r.evidence}</span>}
function card(r:RecordItem){return <button key={r.id} className="task-card" disabled={saving} onClick={()=>setDetail(r)} draggable={connected&&!saving} onDragStart={e=>e.dataTransfer.setData('text/plain',r.id)}><span className="card-top"><span className={'priority '+r.priority.toLowerCase()}>{r.priority}</span><span>{r.id}</span><span className="card-dots">···</span></span><h3>{r.title}</h3><p>{r.body.split('\n')[0]}</p><span className="card-bottom"><span className="tag">{r.category}</span><span>{r.owner||'未分配'}</span></span>{r.due&&<span className="due"><Clock size={13}/> {r.due}</span>}</button>}
function board(list:RecordItem[]){return <div className="board">{statuses.map((s,i)=><section className={'lane lane-'+i} key={s} onDragOver={e=>{if(connected&&!saving)e.preventDefault()}} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');const item=records.find(r=>r.id===id&&r.kind==='task');if(item){if(s==='已完成'){setEditing({...item,status:s});return;}persist(records.map(r=>r.id===id?{...r,status:s,updatedAt:new Date().toISOString()}:r),'任务状态已保存')}}}><div className="lane-title"><span className="dot"/>{s}<span className="count">{list.filter(r=>r.status===s).length}</span><button aria-label={'新建'+s+'任务'} disabled={!connected} onClick={()=>{create('task');setEditing(prev=>prev?{...prev,status:s}:null)}}><Plus size={17}/></button></div><div className="lane-cards">{list.filter(r=>r.status===s).map(card)}{!list.some(r=>r.status===s)&&<div className="lane-empty"><span>{i===3?'✓':'—'}</span>{i===3?'验收通过后，记录在这里':'暂无'+s+'任务'}<small>拖入任务或在详情中修改状态</small></div>}</div></section>)}</div>}
const viewName=nav.find(n=>n[0]===view)?.[1];
return <SidebarProvider style={{'--sidebar-width':'15.5rem'} as React.CSSProperties}><Sidebar className="studio-sidebar"><SidebarHeader className="brand"><div className="brand-mark">20<span>代</span></div><div><strong>我的20代生活</strong><small>GAME DESIGN WORKSPACE</small></div></SidebarHeader><SidebarContent><div className="nav-label">项目工作区</div><SidebarMenu>{nav.map(([key,label,Icon])=><SidebarMenuItem key={key}><SidebarMenuButton isActive={view===key} onClick={()=>go(key)} className="nav-button"><Icon size={19}/><span>{label}</span>{key==='task'&&<b>{tasks.filter(t=>t.status!=='已完成').length}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-project"><span className="eyebrow">当前阶段</span><h3>概念与规则定义</h3><p>把已有想法整理成<br/>可以验证的游戏规则。</p><span className="side-pill"><span/>制作进度待记录</span></div></SidebarContent><SidebarFooter><div className="side-profile"><span className="avatar">主</span><div><strong>主策工作台</strong><small>项目决策 · 个人空间</small></div></div></SidebarFooter></Sidebar>
<SidebarInset><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>我的20代生活</span><ChevronRight size={14}/><strong>{viewName}</strong></div><span className="save-state"><span className={connected?'online':''}/>{saving?'正在保存…':loading?'正在读取…':connected?'云端已保存 · 跨设备同步':'资料预览'}</span></header><main className="workspace"><section className="page-heading"><div><span className="eyebrow">PROJECT / {view==='overview'?'01':String(nav.findIndex(n=>n[0]===view)+1).padStart(2,'0')}</span><h1>{view==='overview'?'我的20代生活':viewName}<span className="heading-dot">.</span></h1><p>{view==='overview'?'Steam · 2D 都市人生养成｜从生活选择，到不同的人生。':view==='task'?'把规则空缺变成任务。拖动卡片更新进度，完成前记录验收依据。':view==='idea'?'保留每个原始想法，区分内容方向与已定规则。':view==='mechanic'?'从操作、条件与反馈，检查系统是否真正相连。':view==='doc'?'维护同一份项目依据，保留尚未确定的设计。':view==='assistant'?'随时讨论想法；新建或实质修改记录后自动审查。':'66 条对话 · 5 张原图 · 完整导出说明'}</p></div><div className="heading-actions"><button className="button secondary" onClick={()=>download('我的20代生活-工作台备份.json',JSON.stringify({version:1,records,assistantHistory:assistant.jobs},null,2),'application/json')}><Download size={16}/>导出资料</button><input ref={importInput} type="file" accept=".json,application/json" hidden onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(f.size>2000000){setError('备份文件超过 2 MB。');return;}try{receiveBackup(JSON.parse(await f.text()))}catch{setError('无法读取 JSON 备份。')}}}/><button className="button secondary" disabled={!connected} onClick={()=>importInput.current?.click()}>导入备份</button>{view!=='source'&&view!=='assistant'&&<button className="button primary" disabled={!connected} onClick={()=>create(view==='overview'?'task':view)}><Plus size={17}/>新建{view==='idea'?'灵感':view==='doc'?'文档':view==='mechanic'?'机制':'任务'}</button>}</div></section>
{error&&<div className="error" role="alert">{error}<button onClick={()=>void reload()}><RefreshCw size={14}/>重新读取</button></div>}
{view==='assistant'&&<AssistantPanel assistant={assistant} records={records} onOpen={id=>setDetail(records.find(r=>r.id===id)||null)}/>}
{view==='overview'&&<><div className="overview-grid"><section className="focus-panel"><div className="focus-top"><span className="tag">NEXT MILESTONE</span><span>01 / 规则定义</span></div><h2>先把「一天怎么玩」定下来。</h2><p>每日操作、时间推进、状态变量仍未明确。<br/>完成这三项，再评审首个可玩切片的范围。</p><button onClick={()=>{go('task');setFilter('核心循环')}}>查看核心循环任务 <ArrowUpRight size={18}/></button><span className="focus-index" aria-hidden="true">01</span></section><section className="progress-panel"><div className="section-top"><h2>任务进度</h2><span className="tag">{done} / {tasks.length}</span></div><div className="percentage">{percent}<span>%</span></div><Progress value={percent} aria-label="已完成任务比例"/><p>仅统计已完成任务；不代表游戏完工率。</p><div className="progress-foot"><span><i className="dot"/> {tasks.filter(r=>r.status==='进行中').length} 进行中</span><span>{tasks.filter(r=>r.status==='待验收').length} 待验收</span></div></section></div>
<div className="stat-row">{[['idea','灵感记录',Lightbulb],['mechanic','机制草案',Workflow],['doc','GDD 文档',BookOpen],['source','原始图片',ImageIcon]].map(([k,label,Icon])=><button key={k as string} onClick={()=>go(k as string)} className="stat"><Icon size={22}/><span>{label as string}</span><strong>{k==='source'?5:records.filter(r=>r.kind===k).length}</strong><ArrowUpRight size={16}/></button>)}</div>
<div className="section-top section-space"><div><h2>优先处理</h2><p>从资料中提取的 P0 任务，均未假设已开工。</p></div><button className="text-button" onClick={()=>go('task')}>全部任务 <ArrowRight size={16}/></button></div>{board(tasks.filter(r=>r.priority==='P0'))}
<div className="bottom-grid"><section className="panel"><div className="section-top"><h2>设计边界</h2><span className="tag violet">依据原文</span></div><div className="decision-row"><Check size={17}/><span>Steam / 2D / 可以不恋爱</span><span className="mini">用户明确</span></div><div className="decision-row"><Clock size={17}/><span>年龄范围、好友结构、焦虑阈值</span><span className="mini">待确认</span></div><button className="text-button" onClick={()=>setDetail(records.find(r=>r.title.includes('决策与冲突'))||null)}>查看决策与冲突清单 <ArrowUpRight size={15}/></button></section><section className="panel source-summary"><div><span className="eyebrow">SOURCE ARCHIVE</span><h2>想法有出处，修改有依据。</h2><p>原文与原图保留，历史助手建议单独标记。</p><button className="text-button" onClick={()=>go('source')}>打开原始资料 <ArrowUpRight size={16}/></button></div><FolderOpen size={54} strokeWidth={1}/></section></div></>}
{['task','idea','mechanic','doc'].includes(view)&&<><div className="toolbar"><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索标题、正文或来源" aria-label="搜索记录"/></label><Choice label="筛选模块" value={filter} options={['全部模块',...Array.from(new Set(records.filter(r=>r.kind===view).map(r=>r.category)))]} onChange={setFilter}/><span>{shown.length} 项</span>{view==='doc'&&<button className="text-button" onClick={()=>download('我的20代生活-GDD.md',records.filter(r=>r.kind==='doc').map(r=>`# ${r.title}\n\n${r.body}\n\n来源：${r.source}\n`).join('\n---\n'))}>导出 GDD <Download size={15}/></button>}</div>{view==='task'?board(shown):view==='doc'?<div className="document-list">{shown.map((r,i)=><button key={r.id} className="document-row" onClick={()=>setDetail(r)}><span className="doc-number">{String(i).padStart(2,'0')}</span><FileText size={23}/><div><h3>{r.title}</h3><p>{r.category} · {r.body.slice(0,95).replace(/#/g,'')}</p></div>{evidence(r)}<ArrowUpRight size={19}/></button>)}</div>:<div className="library-grid">{shown.map(r=><button key={r.id} className={'library-card '+(view==='idea'?'idea-card':'')} onClick={()=>setDetail(r)}><div className="card-top"><span className="tag">{r.category}</span>{evidence(r)}</div><h2>{r.title}</h2><p>{r.body}</p><footer><LinkIcon size={13}/><span>{r.source}</span><ArrowUpRight size={16}/></footer></button>)}</div>}{!shown.length&&<div className="empty">没有符合条件的记录<button className="text-button" onClick={()=>{setQuery('');setFilter('全部模块')}}>清除筛选</button></div>}</>}
{view==='source'&&<><div className="toolbar"><Tabs value={sourceTab} onValueChange={setSourceTab}><TabsList><TabsTrigger value="images">图片原件 · 5</TabsTrigger><TabsTrigger value="transcript">聊天全文 · 66</TabsTrigger><TabsTrigger value="readme">导出说明</TabsTrigger></TabsList></Tabs><a className="text-button" href="/sources/transcript_user_visible.md" download>下载聊天原文 <Download size={15}/></a></div>{sourceTab==='images'?<div className="image-grid">{sources.assets.map(a=><article className="image-card" key={a.name}><button className="image-preview" onClick={()=>setImage(a.url)}><img src={a.url} alt={a.title} loading="lazy"/><span>查看完整原图 ↗</span></button><div><small>{a.name}</small><h2>{a.title}</h2><p>{a.text}</p><a href={a.url} download>下载原图 <Download size={14}/></a></div></article>)}</div>:sourceTab==='readme'?<article className="prose panel">{sources.readme}</article>:<><label className="search full-search"><Search size={17}/><input placeholder="在全部聊天原文中搜索" value={query} onChange={e=>setQuery(e.target.value)} aria-label="搜索聊天原文"/></label><div className="transcript">{sources.blocks.filter(b=>b.text.includes(query)).map(b=><details id={b.id} key={b.id} open={query?true:undefined}><summary><span className={'role '+(b.role==='用户'?'user':'')}>{b.role}</span><b>{b.id}</b><span>L{b.line}</span><p>{b.text.trim().slice(0,100)}</p></summary><pre>{b.text}</pre></details>)}</div></>}</>}
<footer className="workspace-footer"><span>我的20代生活 / 项目工作台</span><span>资料导入于 2026.09.09 · 不推定制作完成</span></footer></main></SidebarInset>
<Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="record-dialog">{detail&&<><DialogTitle>{detail.title}</DialogTitle><DialogDescription>{detail.id} · {detail.category} · {detail.status}</DialogDescription><div className="detail-meta">{evidence(detail)}<span className="tag">{detail.priority}</span>{detail.kind==='task'&&<span>{detail.owner||'未分配'} {detail.due&&' / '+detail.due}</span>}</div><div className="prose detail-body"><DocumentBody text={detail.body}/></div><div className="source-note"><LinkIcon size={15}/><span>来源：{detail.source}</span><button onClick={()=>{const src=detail.source.match(/SRC-\d+/)?.[0];setDetail(null);go('source');setSourceTab(src?'transcript':'images');if(src)setTimeout(()=>document.getElementById(src)?.scrollIntoView({block:'start',behavior:'smooth'}),100)}}>查看资料 <ArrowUpRight size={14}/></button></div><div className="dialog-actions"><button className="button secondary" disabled={!connected} onClick={async()=>{try{await assistant.action({action:'review',recordId:detail.id});setDetail(null);go('assistant');setNotice('已提交审查，请打开“自动审查”查看')}catch(e){setError((e as Error).message)}}}>请橡皮鸭审查</button><button className="button secondary" disabled={!connected} onClick={()=>{setEditing({...detail});setDetail(null)}}><Pencil size={15}/>编辑{detail.kind==='task'?'与更新进度':''}</button>{detail.kind==='idea'&&<button className="button primary" disabled={!connected} onClick={()=>{setEditing({...detail,id:'TASK-'+crypto.randomUUID().slice(0,8),kind:'task',status:'待办',evidence:'整理建议',source:detail.id+' / '+detail.source});setDetail(null)}}>转为任务 <ArrowRight size={15}/></button>}<button className="icon-button danger" aria-label="删除记录" disabled={!connected} onClick={()=>{setRemove(detail);setDetail(null)}}><Trash2 size={18}/></button></div></>}</DialogContent></Dialog>
<Dialog open={!!editing} onOpenChange={v=>!v&&!saving&&setEditing(null)}><DialogContent className="record-dialog">{editing&&<form onSubmit={async e=>{e.preventDefault();if(!editing.title.trim()||!editing.body.trim())return;const item={...editing,title:editing.title.trim(),updatedAt:new Date().toISOString()};if(item.kind==='task'&&item.status==='已完成'&&!/完成依据：\s*\S/.test(item.body)){setError('请在正文中填写“完成依据：”及实际验收结果。');return;}const exists=records.some(r=>r.id===item.id);if(await persist(exists?records.map(r=>r.id===item.id?item:r):[...records,item],'内容已保存'))setEditing(null)}}><DialogTitle>{records.some(r=>r.id===editing.id)?'编辑记录':'新建记录'}</DialogTitle><DialogDescription>保存到项目工作台。原始聊天与图片不会被改写。</DialogDescription><label className="field">标题<input required maxLength={200} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><div className="field-grid"><label className="field">模块<input required value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}/></label><label className="field">优先级<Choice label="优先级" value={editing.priority} options={['P0','P1','P2']} onChange={v=>setEditing({...editing,priority:v})}/></label><label className="field">{editing.kind==='task'?'进度':'内容状态'}<Choice label="内容状态" value={editing.status} options={editing.kind==='task'?statuses:['待确认','用户提出','待定义','整理稿','已确认','历史建议']} onChange={v=>setEditing({...editing,status:v,...(editing.kind!=='task'?{evidence:v}:{})})}/></label>{editing.kind==='task'&&<><label className="field">负责人<input value={editing.owner} placeholder="未分配" onChange={e=>setEditing({...editing,owner:e.target.value})}/></label><label className="field">截止日期<input type="date" value={editing.due} onChange={e=>setEditing({...editing,due:e.target.value})}/></label></>}</div><label className="field">正文 / 规则 / 验收依据<textarea required rows={9} value={editing.body} onChange={e=>setEditing({...editing,body:e.target.value})}/></label><label className="field">来源<input value={editing.source} onChange={e=>setEditing({...editing,source:e.target.value})}/></label>{editing.status==='已完成'&&<p className="hint">请填写“完成依据：”及实际交付或验收结果。</p>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="dialog-actions"><button className="button secondary" type="button" disabled={saving} onClick={()=>setEditing(null)}>取消</button><button className="button primary" disabled={saving||!connected} type="submit">{saving?'保存中…':'保存记录'}</button></div></form>}</DialogContent></Dialog>
<Dialog open={!!image} onOpenChange={v=>!v&&setImage(null)}><DialogContent className="image-dialog"><DialogTitle>图片原件</DialogTitle><DialogDescription>完整截图，可滚动阅读</DialogDescription>{image&&<img src={image} alt="项目原始聊天截图"/>}</DialogContent></Dialog>
<AlertDialog open={!!remove} onOpenChange={v=>!v&&setRemove(null)}><AlertDialogContent><AlertDialogTitle>删除这条记录？</AlertDialogTitle><AlertDialogDescription>{remove?.title}。原始资料仍会保留；删除前可先导出备份。</AlertDialogDescription><div className="dialog-actions"><button className="button secondary" disabled={saving} onClick={()=>setRemove(null)}>取消</button><button className="button primary" disabled={saving} onClick={async()=>{if(await persist(records.filter(r=>r.id!==remove?.id),'记录已删除'))setRemove(null)}}>确认删除</button></div></AlertDialogContent></AlertDialog>
<Dialog open={!!incoming} onOpenChange={v=>!v&&!saving&&setIncoming(null)}><DialogContent className="record-dialog"><DialogTitle>合并旧浏览器资料</DialogTitle><DialogDescription>云端独有记录会保留。导入前建议先导出当前云端资料。</DialogDescription>{incoming&&<><p>备份共 {incoming.length} 条，其中 {incoming.filter(r=>!records.some(c=>c.id===r.id)).length} 条为新增，{incoming.filter(r=>records.some(c=>c.id===r.id&&JSON.stringify(c)!==JSON.stringify(r))).length} 条与云端不同。</p><label className="import-choice"><input type="checkbox" checked={overwrite} onChange={e=>setOverwrite(e.target.checked)}/>用备份版本覆盖同编号的云端记录（默认保留云端版本）</label><p className="hint">旧浏览器数据不会删除。新增或变更的正文会自动排队审查。</p>{error&&<p role="alert">{error}</p>}<div className="dialog-actions"><button className="button secondary" disabled={saving} onClick={()=>setIncoming(null)}>取消</button><button className="button primary" disabled={saving||!connected} onClick={async()=>{const merged=new Map(records.map(r=>[r.id,r]));for(const r of incoming)if(overwrite||!merged.has(r.id))merged.set(r.id,r);if(await persist([...merged.values()],'备份已合并到云端'))setIncoming(null)}}>{saving?'合并中…':'确认合并到云端'}</button></div></>}</DialogContent></Dialog>
{notice&&<div className="toast" role="status"><Check size={17}/>{notice}</div>}
</SidebarProvider>;
}
